const { rollup } = require('rollup');
const resolve = require('@rollup/plugin-node-resolve').default;
const terser = require('@rollup/plugin-terser').default;
const path = require('node:path');

module.exports = async function bundleCode() {
  let bundle;

  try {
    const entryFile = path.resolve(__dirname, '../src/bookmarklet.js');
    bundle = await rollup({
      input: entryFile,
      plugins: [resolve()]
    });

    const code = await generateOutput(bundle);

    console.log();
    console.log(`${code.length} characters:`);
    console.log(code);

    return code;
  } catch (err) {
    console.error(err);
  } finally {
    if (bundle) {
      await bundle.close();
    }
  }
}

async function generateOutput(bundle) {
  const { output } = await bundle.generate({
    format: 'iife',
    plugins: [
      terser({
        module: true,
        ecma: '2022',
        compress: {
          negate_iife: false,
        }
      })
    ]
  });

  for (const chunkOrAsset of output) {
    if (chunkOrAsset.type === 'chunk') {
      return chunkOrAsset.code;
    }
  }

  console.error('No chunks generated by rollup', output);
  throw new Error('No chunks generated by rollup');
}
